import { Article } from '../../modules/article/article.entity';

export const articlesSeed: Article[] = [
  {
    id: 1,
    title: 'カフェスタッフ募集',
    description: '駅前のオシャレなカフェでのアルバイトです。',
    job_detail: '接客やレジ打ちなどの業務を行います。',
    applicant_eligibility: '高校生可、未経験者歓迎',
    application_deadline: new Date('2024-12-31'),
    payment: 1050.0,
    transportation_fee: 500,
    location: '新宿駅西口',
    access: '徒歩5分',
    recruitment_quota: 3,
    current_applicants: 1,
    work_date: new Date('2025-01-15'),
    start_time: '09:00:00',
    end_time: '17:00:00',
    break_time: 60,
    experience_not_required: true,
    image_url:
      'https://saiyo-connect.jp/uploads/accounts/pluswork/storage/62a84705159d2.png',
    created_at: new Date('2024-11-01T10:00:00'),
    updated_at: new Date(),
  },
  {
    id: 2,
    title: 'コンビニスタッフ急募',
    description: '24時間営業のコンビニエンスストアでの募集です。',
    job_detail: 'レジ打ち、商品陳列、清掃などを行います。',
    applicant_eligibility: '18歳以上、夜勤可能な方',
    application_deadline: new Date('2024-12-20'),
    payment: 1200.0,
    transportation_fee: undefined,
    location: '大阪市中央区',
    access: '地下鉄本町駅から徒歩2分',
    recruitment_quota: 5,
    current_applicants: 3,
    work_date: new Date('2025-01-10'),
    start_time: '22:00:00',
    end_time: '06:00:00',
    break_time: 60,
    experience_not_required: false,
    image_url:
      'https://jobty.aldev.designserver.space/wp/wp-content/uploads/2018/04/2acd5216257006606faec17be334de59.jpg',
    created_at: new Date('2024-11-05T14:30:00'),
    updated_at: new Date(),
  },
  {
    id: 3,
    title: 'イベントスタッフ募集',
    description: '大型コンサートでのスタッフ業務です。',
    job_detail: '会場設営、来場者の案内などを行います。',
    applicant_eligibility: '健康な方、体力に自信のある方',
    application_deadline: new Date('2024-12-15'),
    payment: 950.0,
    transportation_fee: 1000,
    location: 'さいたまスーパーアリーナ',
    access: '最寄り駅から徒歩10分',
    recruitment_quota: 20,
    current_applicants: 15,
    work_date: new Date('2025-02-05'),
    start_time: '12:00:00',
    end_time: '22:00:00',
    break_time: 120,
    experience_not_required: true,
    image_url:
      'https://c74.s3.indeed.com/0c4d8382-b619-4bc5-9fd6-1500c1da143a@medium',
    created_at: new Date('2024-11-10T09:00:00'),
    updated_at: new Date(),
  },
  {
    id: 4,
    title: '工場ライン作業員募集',
    description: '食品工場でのライン作業スタッフを募集します。',
    job_detail: '食品のパッケージングや検品作業を行います。',
    applicant_eligibility: '未経験者歓迎、長期勤務可能な方',
    application_deadline: new Date('2024-12-25'),
    payment: 1100.0,
    transportation_fee: 800,
    location: '神奈川県川崎市',
    access: 'JR川崎駅からバス15分',
    recruitment_quota: 10,
    current_applicants: 5,
    work_date: new Date('2025-01-20'),
    start_time: '08:00:00',
    end_time: '17:00:00',
    break_time: 60,
    experience_not_required: true,
    image_url:
      'https://sumijob.com/column/wp-content/uploads/2023/08/factorywork-linesagyo.jpg',
    created_at: new Date('2024-11-12T11:00:00'),
    updated_at: new Date(),
  },
  {
    id: 5,
    title: 'ホテルフロントスタッフ',
    description: '高級ホテルでのフロント業務です。',
    job_detail: 'チェックイン・チェックアウト対応、電話応対などを行います。',
    applicant_eligibility: '英語が話せる方、接客経験者優遇',
    application_deadline: new Date('2024-12-30'),
    payment: 1300.0,
    transportation_fee: 1000,
    location: '京都市東山区',
    access: '京阪祇園四条駅から徒歩3分',
    recruitment_quota: 2,
    current_applicants: 1,
    work_date: new Date('2025-02-01'),
    start_time: '14:00:00',
    end_time: '22:00:00',
    break_time: 60,
    experience_not_required: false,
    image_url:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQC1JxYqkrQy3QTxIaKNXBlzltKMriGSUNBdA&s',
    created_at: new Date('2024-11-15T09:00:00'),
    updated_at: new Date(),
  },
  {
    id: 6,
    title: 'データ入力スタッフ',
    description: 'オフィスでのデータ入力作業です。',
    job_detail: '専用ソフトを使ってデータを入力します。',
    applicant_eligibility: '基本的なPC操作ができる方',
    application_deadline: new Date('2024-12-28'),
    payment: 1000.0,
    transportation_fee: 500,
    location: '福岡市博多区',
    access: '地下鉄天神駅から徒歩5分',
    recruitment_quota: 4,
    current_applicants: 2,
    work_date: new Date('2025-01-25'),
    start_time: '09:00:00',
    end_time: '18:00:00',
    break_time: 60,
    experience_not_required: true,
    image_url:
      'https://www.froma.com/s/contents/assets/images/S10070B/a19001/main_image_sp.png',
    created_at: new Date('2024-11-18T13:00:00'),
    updated_at: new Date(),
  },
  {
    id: 7,
    title: '飲食店ホールスタッフ',
    description: '和食レストランでのホール業務です。',
    job_detail: 'お客様の案内、オーダー取り、配膳などを行います。',
    applicant_eligibility: '高校生可、笑顔で接客できる方',
    application_deadline: new Date('2024-12-22'),
    payment: 1020.0,
    transportation_fee: undefined,
    location: '札幌市中央区',
    access: '地下鉄大通駅から徒歩2分',
    recruitment_quota: 5,
    current_applicants: 3,
    work_date: new Date('2025-01-18'),
    start_time: '17:00:00',
    end_time: '23:00:00',
    break_time: 30,
    experience_not_required: true,
    image_url:
      'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS50heyu2IjdpX7Aa5wS_Rn66HVZ-py5AnEBQ&s',
    created_at: new Date('2024-11-20T15:00:00'),
    updated_at: new Date(),
  },
  {
    id: 8,
    title: '引越しスタッフ募集',
    description: '引越し作業の補助スタッフを募集します。',
    job_detail: '荷物の運搬、梱包などを行います。',
    applicant_eligibility: '体力に自信のある方',
    application_deadline: new Date('2024-12-18'),
    payment: 1250.0,
    transportation_fee: 700,
    location: '名古屋市中村区',
    access: 'JR名古屋駅から徒歩10分',
    recruitment_quota: 8,
    current_applicants: 6,
    work_date: new Date('2025-01-12'),
    start_time: '08:00:00',
    end_time: '17:00:00',
    break_time: 60,
    experience_not_required: true,
    image_url:
      'https://the0123-job.net/jobfind-pc/job/9060/image/thirdly_large',
    created_at: new Date('2024-11-22T08:00:00'),
    updated_at: new Date(),
  },
  {
    id: 9,
    title: 'アパレル販売スタッフ',
    description: 'ファッションブランドでの販売業務です。',
    job_detail: '接客、商品整理、レジ打ちなどを行います。',
    applicant_eligibility: 'おしゃれが好きな方、接客経験者優遇',
    application_deadline: new Date('2024-12-26'),
    payment: 1100.0,
    transportation_fee: 500,
    location: '渋谷区',
    access: '渋谷駅から徒歩5分',
    recruitment_quota: 3,
    current_applicants: 2,
    work_date: new Date('2025-01-22'),
    start_time: '10:00:00',
    end_time: '19:00:00',
    break_time: 60,
    experience_not_required: false,
    image_url:
      'https://recpar-ats.s3.amazonaws.com/media/images/job_offer/ma28_job_offer_1484577_image3.jpg',
    created_at: new Date('2024-11-25T12:00:00'),
    updated_at: new Date(),
  },
  {
    id: 10,
    title: '試験監督アルバイト',
    description: '大学入試の試験監督業務です。',
    job_detail: '受験生の案内、試験中の監督を行います。',
    applicant_eligibility: '大学生以上、責任感のある方',
    application_deadline: new Date('2024-12-29'),
    payment: 1500.0,
    transportation_fee: 1000,
    location: '東京都千代田区',
    access: 'JR御茶ノ水駅から徒歩7分',
    recruitment_quota: 15,
    current_applicants: 10,
    work_date: new Date('2025-02-02'),
    start_time: '08:00:00',
    end_time: '17:00:00',
    break_time: 60,
    experience_not_required: true,
    image_url:
      'https://kyujinbox.k-img.com/images/crawl/1502/8b37e3256d266607e751edc3e7d7c5ce/3/5fc2816aa0eebc1898deec2be93447dd.jpeg',
    created_at: new Date('2024-11-28T09:00:00'),
    updated_at: new Date(),
  },
];
